### ISSUE TITLE
default fontFamily change not working

### ISSUE THREAD

**Issue by Coachonko** [windicss/windicss-webpack-plugin#120]
My configuration
```js
import { defineConfig } from 'windicss/helpers';

export default defineConfig( {
  extract: {
    include: [
      './src/**/*.{html,js,jsx,css}',
      './public/**/*.{html,js,jsx,css}'
    ],
  },
  theme: {
    fontFamily: {
      "sans": [
        "Candid",
        ...defaultTheme.fontFamily.sans
      ],
    },
  },
} );
```
Out puts
```css
.font-sans {
  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
```
The string `"Candid"` is ignored, in fact I think the setting is ignored entirely. The configuration
```js
import { defineConfig } from 'windicss/helpers';

export default defineConfig( {
  extract: {
    include: [
      './src/**/*.{html,js,jsx,css}',
      './public/**/*.{html,js,jsx,css}'
    ],
  },
  theme: {
    fontFamily: {
      "sans": [
        "deez walnuts"
      ],
    },
  },
} );
```
Outputs the same
```css
.font-sans {
  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
}
```
